spring:
  application:
    name: dynamictp
  dynamictp:
    core-pool-size: 5
    maximum-pool-size: 10
    keep-alive-time: 30
    time-unit: seconds
    queue-name: "myQueue"
    capacity: 10
    fair: true
    thread-pool-name: "testThreadPoolName"
    reject-handler-name: "testRejectHandler"


